name: Check PR Description for Issue Number

on:
  pull_request:
    types: [opened, edited, reopened]
  workflow_dispatch:

jobs:
  check_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR description and existing PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issuePattern = /#\d+/;
            const { owner, repo } = context.repo;

            async function checkPRDescription(pr) {
              const prDescription = pr.body || "";
              if (!issuePattern.test(prDescription)) {
                console.log(`Issue number missing in PR #${pr.number}`);
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: pr.number,
                  body: 'Please include the issue number in the PR description. Format: #<issue_number>'
                });
                return false;
              }
              return true;
            }

            // Check the current PR
            if (context.payload.pull_request) {
              await checkPRDescription(context.payload.pull_request);
            }

            // Check existing open PRs
            const openPRs = await github.paginate(github.rest.pulls.list, {
              owner,
              repo,
              state: 'open',
              per_page: 100
            });

            for (const pr of openPRs) {
              await checkPRDescription(pr);
            }
